[package]
name = "sp-auto-id"
version = "0.1.0"
authors = ["Vedhavyas Singareddi <ved@subspace.network>"]
edition.workspace = true
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
description = "Primitives for AutoId"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
sp-core.workspace = true
sp-externalities.workspace = true
sp-runtime-interface.workspace = true
subspace-runtime-primitives.workspace = true
x509-parser = { workspace = true, features = ["verify"], optional = true }

[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    "scale-info/std",
    "sp-core/std",
    "sp-externalities/std",
    "sp-runtime-interface/std",
    "subspace-runtime-primitives/std",
    "x509-parser"
]

runtime-benchmarks = []
