[package]
name = "domain-runtime-primitives"
version = "0.1.0"
authors = ["Subspace Labs <https://subspace.network>"]
edition.workspace = true
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
description = "Common primitives of subspace domain runtime"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
fp-account = { workspace = true, features = ["serde"] }
frame-support.workspace = true
frame-system.workspace = true
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["alloc", "derive"] }
sp-api.workspace = true
sp-core.workspace = true
sp-runtime.workspace = true
subspace-core-primitives.workspace = true
subspace-runtime-primitives.workspace = true
sp-weights.workspace = true

[features]
default = ["std"]
std = [
    "fp-account/std",
    "frame-support/std",
    "frame-system/std",
    "parity-scale-codec/std",
    "scale-info/std",
    "serde/std",
    "sp-api/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-weights/std",
    "subspace-core-primitives/std",
    "subspace-runtime-primitives/std",
]
