[package]
name = "domain-check-weight"
version = "0.1.0"
authors = ["Subspace Labs <https://subspace.network>"]
edition.workspace = true
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
description = "Subspace domain check_weight extension"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive"] }
frame-support.workspace = true
frame-system.workspace = true
scale-info = { workspace = true, features = ["derive"] }
sp-runtime.workspace = true
sp-weights.workspace = true

[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    "frame-support/std",
    "frame-system/std",
    "scale-info/std",
    "sp-runtime/std",
    "sp-weights/std",
]
