[package]
name = "cross-domain-message-gossip"
version = "0.1.0"
authors = ["Vedhavyas Singareddi <ved@subspace.network>"]
edition.workspace = true
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
description = "Subspace message relayer."
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
domain-block-preprocessor.workspace = true
fp-account.workspace = true
futures.workspace = true
parity-scale-codec = { workspace = true, features = ["derive"] }
parking_lot.workspace = true
sc-client-api.workspace = true
sc-executor.workspace = true
sc-network.workspace = true
sc-network-gossip.workspace = true
sc-transaction-pool-api.workspace = true
sc-utils.workspace = true
sp-api.workspace = true
sp-blockchain.workspace = true
sp-consensus.workspace = true
sp-core.workspace = true
sp-domains.workspace = true
sp-messenger.workspace = true
sp-runtime.workspace = true
subspace-runtime-primitives.workspace = true
thiserror.workspace = true
tracing.workspace = true
