[package]
name = "subspace-metrics"
version = "0.1.0"
edition.workspace = true
authors = [
    "Shamil Gadelshin <shamilgadelshin@gmail.com>"
]
description = "Metrics for Subspace Network"
license = "0BSD"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
actix-web = { workspace = true, features = ["macros"] }
prometheus.workspace = true
prometheus-client.workspace = true
tracing.workspace = true
