[package]
name = "pallet-domain-id"
version = "0.1.0"
authors = ["Subspace Labs <https://subspace.network>"]
edition.workspace = true
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
description = "Subspace node pallet to store domain id."
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive"] }
frame-support.workspace = true
frame-system.workspace = true
scale-info = { workspace = true, features = ["derive"] }
sp-domains.workspace = true
sp-runtime.workspace = true

[dev-dependencies]
sp-core.workspace = true
sp-io.workspace = true
subspace-runtime-primitives.workspace = true

[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    "frame-support/std",
    "frame-system/std",
    "scale-info/std",
    "sp-domains/std",
    "sp-runtime/std",
]

runtime-benchmarks = []
