[package]
name = "sp-objects"
version = "0.1.0"
authors = ["Vedhavyas Singareddi <ved@subspace.network>"]
edition.workspace = true
license = "0BSD"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
description = "Primitives for Objects"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-api.workspace = true
subspace-core-primitives.workspace = true
subspace-runtime-primitives.workspace = true

[features]
default = ["std"]
std = [
    "sp-api/std",
    "subspace-core-primitives/std",
    "subspace-runtime-primitives/std",
]
