[package]
name = "sp-domain-sudo"
version = "0.1.0"
authors = ["Vedhavyas Singareddi <ved@subspace.network>"]
edition.workspace = true
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
description = "Primitives of pallet domain sudo"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
async-trait = { workspace = true, optional = true }
parity-scale-codec = { workspace = true, features = ["derive"] }
sp-api.workspace = true
sp-inherents.workspace = true

[features]
default = ["std"]
std = [
    "async-trait",
    "parity-scale-codec/std",
    "sp-api/std",
    "sp-inherents/std",
]
