[package]
name = "subspace-proof-of-space-gpu"
description = "Subspace proof of space implementation for GPU (low-level proving utilities)"
license = "0BSD"
version = "0.1.0"
authors = ["Supranational LLC"]
edition.workspace = true
include = [
    "/build.rs",
    "/src",
    "/Cargo.toml",
    "/README.md",
]

[dependencies]
blst = { workspace = true, optional = true }
rust-kzg-blst = { workspace = true, optional = true }
# TODO: Fork with ROCm support, switch to upstream once `rocm` branch from `https://github.com/dot-asm/sppark` + https://github.com/dot-asm/sppark/pull/2 are upstreamed
sppark = { workspace = true, optional = true }
subspace-core-primitives = { workspace = true, optional = true }
subspace-kzg = { workspace = true, optional = true }

[dev-dependencies]
subspace-erasure-coding.workspace = true
subspace-farmer-components.workspace = true
subspace-proof-of-space.workspace = true

[build-dependencies]
cc.workspace = true

[features]
# Only Volta+ architectures are supported (GeForce RTX 16xx consumer GPUs and newer)
cuda = ["_gpu", "sppark/cuda"]
# TODO: ROCm can't be enabled at the same time as `cuda` feature at the moment
# Seems to support RDNA 2+, at least on Linux
rocm = ["_gpu", "sppark/rocm"]
# Internal feature, shouldn't be used directly
_gpu = [
    "dep:blst",
    "dep:rust-kzg-blst",
    "dep:subspace-core-primitives",
    "dep:subspace-kzg",
]
