[package]
name = "domain-eth-service"
version = "0.1.0"
authors = ["Vedhavyas Singareddi <ved@subspace.network>"]
edition.workspace = true
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
description = "Ethereum compatible core component service"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
clap = { workspace = true, features = ["derive"] }
domain-runtime-primitives.workspace = true
domain-service.workspace = true
fc-consensus.workspace = true
fc-db.workspace = true
fc-mapping-sync.workspace = true
fc-rpc = { workspace = true, features = ["rpc-binary-search-estimate"] }
fc-rpc-core.workspace = true
fc-storage.workspace = true
fp-rpc = { workspace = true, features = ["default"] }
futures.workspace = true
jsonrpsee = { workspace = true, features = ["server-core"] }
pallet-transaction-payment-rpc.workspace = true
parity-scale-codec.workspace = true
sc-client-api.workspace = true
sc-rpc.workspace = true
sc-rpc-server.workspace = true
sc-network-sync.workspace = true
sc-service.workspace = true
sc-transaction-pool.workspace = true
sc-transaction-pool-api.workspace = true
serde = { workspace = true, features = ["derive"] }
sp-api.workspace = true
sp-block-builder.workspace = true
sp-blockchain.workspace = true
sp-core.workspace = true
sp-inherents.workspace = true
sp-runtime.workspace = true
substrate-frame-rpc-system.workspace = true
