[package]
name = "subspace-proof-of-time"
description = "Subspace proof of time implementation"
license = "0BSD"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition.workspace = true
include = [
    "/src",
    "/Cargo.toml",
]

[lib]
# Necessary for CLI options to work on benches
bench = false

[dependencies]
aes.workspace = true
subspace-core-primitives.workspace = true
thiserror.workspace = true

[target.'cfg(target_arch = "x86_64")'.dependencies]
cpufeatures = { workspace = true }

[dev-dependencies]
core_affinity.workspace = true
criterion.workspace = true
rand_core = { workspace = true }
rand_chacha = { workspace = true }

[[bench]]
name = "pot"
harness = false

[[bench]]
name = "pot-compare-cpu-cores"
harness = false
