[package]
name = "domain-pallet-executive"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>", "Subspace Labs <admin@subspace.network>"]
edition.workspace = true
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace/"
description = "Cirrus executives engine"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive"] }
frame-benchmarking = { workspace = true, optional = true }
frame-executive.workspace = true
frame-support.workspace = true
frame-system.workspace = true
log.workspace = true
scale-info = { workspace = true, features = ["derive"] }
sp-executive.workspace = true
sp-io.workspace = true
sp-runtime.workspace = true
sp-std.workspace = true
sp-tracing.workspace = true

[dev-dependencies]
pallet-balances = { workspace = true, features = ["std"] }
sp-core.workspace = true
sp-externalities.workspace = true
sp-version.workspace = true
subspace-runtime-primitives = { workspace = true, features = ["std"] }

[features]
default = ["std"]
with-tracing = ["sp-tracing/with-tracing"]
std = [
    "parity-scale-codec/std",
    "frame-benchmarking?/std",
    "frame-executive/std",
    "frame-support/std",
    "frame-system/std",
    "log/std",
    "scale-info/std",
    "sp-executive/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-tracing/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
    "frame-benchmarking/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
]
