[package]
name = "pallet-block-fees"
version = "0.1.0"
authors = ["Subspace Labs <https://subspace.network>"]
edition.workspace = true
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
description = "Subspace node pallet for charging and re-distributing domain transaction fees"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive"] }
domain-runtime-primitives.workspace = true
frame-support.workspace = true
frame-system.workspace = true
pallet-transaction-payment.workspace = true
scale-info = { workspace = true, features = ["derive"] }
sp-block-fees.workspace = true
sp-domains.workspace = true
sp-runtime.workspace = true
sp-std.workspace = true

[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    "domain-runtime-primitives/std",
    "frame-support/std",
    "frame-system/std",
    "scale-info/std",
    "sp-block-fees/std",
    "sp-domains/std",
    "sp-runtime/std",
    "sp-std/std",
]
