[package]
name = "sp-subspace-mmr"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
description = "Primitives for Subspace MMR"
license = "0BSD"
version = "0.1.0"
authors = ["Subspace Labs <https://subspace.network>"]
edition.workspace = true
include = [
    "/src",
    "/Cargo.toml",
]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive"] }
scale-info = { workspace = true, features = ["derive"] }
sp-api.workspace = true
sp-blockchain = { workspace = true, optional = true }
sp-core.workspace = true
sp-externalities.workspace = true
sp-mmr-primitives.workspace = true
sp-runtime.workspace = true
sp-runtime-interface.workspace = true
subspace-core-primitives.workspace = true

[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    "scale-info/std",
    "sp-api/std",
    "sp-blockchain",
    "sp-core/std",
    "sp-externalities/std",
    "sp-mmr-primitives/std",
    "sp-runtime/std",
    "sp-runtime-interface/std",
    "subspace-core-primitives/std"
]
