[package]
name = "subspace-gateway-rpc"
version = "0.1.0"
authors = ["Teor <teor@riseup.net>"]
description = "A Subspace Network data gateway."
edition.workspace = true
license = "0BSD"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
hex.workspace = true
jsonrpsee = { workspace = true, features = ["client-core", "server-core", "macros"] }
serde = { workspace = true, features = ["alloc", "derive"] }
subspace-core-primitives.workspace = true
subspace-data-retrieval.workspace = true
thiserror.workspace = true
tracing.workspace = true
