[package]
name = "sp-block-fees"
version = "0.1.0"
authors = ["Subspace Labs <https://subspace.network>"]
edition.workspace = true
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
description = "Primitives of pallet block-fees"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
async-trait = { workspace = true, optional = true }
parity-scale-codec = { workspace = true, features = ["derive"] }
domain-runtime-primitives.workspace = true
sp-inherents.workspace = true
sp-std.workspace = true

[features]
default = ["std"]
std = [
    "async-trait",
    "parity-scale-codec/std",
    "domain-runtime-primitives/std",
    "sp-inherents/std",
    "sp-std/std",
]
