[package]
name = "subspace-erasure-coding"
description = "Polynomial erasure coding implementation used in Subspace Network"
license = "0BSD"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition.workspace = true
include = [
    "/src",
    "/Cargo.toml",
]

[lib]
# Necessary for CLI options to work on benches
bench = false

[dependencies]
kzg.workspace = true
rust-kzg-blst.workspace = true
subspace-core-primitives.workspace = true
subspace-kzg.workspace = true

[dev-dependencies]
rust-kzg-blst = { workspace = true, features = ["rand"] }
criterion.workspace = true
rand.workspace = true

[features]
default = ["std", "parallel"]
std = [
    "kzg/std",
    "rust-kzg-blst/std",
    "subspace-core-primitives/std",
    "subspace-kzg/std",
]
parallel = ["rust-kzg-blst/parallel"]

[[bench]]
name = "commitments"
harness = false
