[package]
name = "pallet-auto-id"
version = "0.1.0"
authors = ["Subspace Labs <https://subspace.network>"]
edition.workspace = true
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
description = "Auto ID pallet"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive"] }
frame-benchmarking = { workspace = true, optional = true }
frame-support.workspace = true
frame-system.workspace = true
pallet-timestamp = { workspace = true, optional = true }
scale-info = { workspace = true, features = ["derive"] }
sp-auto-id.workspace = true
sp-core.workspace = true
sp-runtime.workspace = true
subspace-runtime-primitives.workspace = true

[dev-dependencies]
pem.workspace = true
ring.workspace = true
sp-io.workspace = true
x509-parser.workspace = true

[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    "frame-benchmarking?/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-timestamp",
    "scale-info/std",
    "sp-auto-id/std",
    "sp-core/std",
    "sp-runtime/std",
    "subspace-runtime-primitives/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
    "frame-benchmarking/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "pallet-timestamp",
    "pallet-timestamp/runtime-benchmarks",
    "sp-auto-id/runtime-benchmarks",
]
