[package]
name = "domain-service"
version = "0.1.0"
authors = ["Anonymous"]
description = "A new Cumulus FRAME-based Substrate Node, ready for hacking together a parachain."
license = "Unlicense"
homepage = "https://substrate.io"
repository = "https://github.com/paritytech/cumulus/"
edition.workspace = true
build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-channel.workspace = true
async-trait.workspace = true
cross-domain-message-gossip.workspace = true
domain-block-builder.workspace = true
domain-block-preprocessor.workspace = true
domain-client-consensus-relay-chain.workspace = true
domain-client-message-relayer.workspace = true
domain-client-operator.workspace = true
domain-runtime-primitives.workspace = true
frame-benchmarking = { workspace = true, optional = true }
futures.workspace = true
jsonrpsee = { workspace = true, features = ["server-core"] }
log.workspace = true
pallet-transaction-payment-rpc.workspace = true
parity-scale-codec.workspace = true
sp-io.workspace = true
sc-chain-spec.workspace = true
sc-client-api.workspace = true
sc-client-db.workspace = true
sc-consensus.workspace = true
sc-domains.workspace = true
sc-executor.workspace = true
sc-informant.workspace = true
sc-network.workspace = true
sc-network-common.workspace = true
sc-network-sync.workspace = true
sc-network-transactions.workspace = true
sc-rpc.workspace = true
sc-rpc-server.workspace = true
sc-service.workspace = true
sc-telemetry.workspace = true
sc-transaction-pool.workspace = true
sc-transaction-pool-api.workspace = true
sc-utils.workspace = true
serde = { workspace = true, features = ["derive"] }
sp-api.workspace = true
sp-block-builder.workspace = true
sp-blockchain.workspace = true
sp-consensus.workspace = true
sp-consensus-slots.workspace = true
sp-core.workspace = true
sp-domains.workspace = true
sp-domains-fraud-proof.workspace = true
sp-messenger.workspace = true
sp-messenger-host-functions.workspace = true
sp-mmr-primitives.workspace = true
sp-offchain.workspace = true
sp-runtime.workspace = true
sp-session.workspace = true
sp-subspace-mmr.workspace = true
sp-transaction-pool.workspace = true
subspace-core-primitives.workspace = true
subspace-runtime-primitives.workspace = true
substrate-frame-rpc-system.workspace = true
substrate-prometheus-endpoint.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[build-dependencies]
substrate-build-script-utils.workspace = true

[features]
runtime-benchmarks = [
    "dep:frame-benchmarking",
    "sc-domains/runtime-benchmarks",
]
