[package]
name = "sp-domains"
version = "0.1.0"
authors = ["Subspace Labs <https://subspace.network>"]
edition.workspace = true
license = "0BSD"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
description = "Primitives of domains pallet"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
blake2.workspace = true
domain-runtime-primitives.workspace = true
frame-support.workspace = true
hash-db.workspace = true
memory-db.workspace = true
hex-literal.workspace = true
parity-scale-codec = { workspace = true, features = ["derive"] }
rand.workspace = true
rand_chacha.workspace = true
rs_merkle.workspace = true
scale-info = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["alloc", "derive"] }
sp-api.workspace = true
sp-application-crypto.workspace = true
sp-core.workspace = true
sp-runtime.workspace = true
sp-runtime-interface.workspace = true
sp-state-machine.workspace = true
sp-std.workspace = true
sp-trie.workspace = true
sp-version.workspace = true
sp-weights.workspace = true
subspace-core-primitives.workspace = true
subspace-runtime-primitives.workspace = true
trie-db.workspace = true

# test-ethereum dependencies
ethereum = { workspace = true, optional = true }
fp-self-contained = { workspace = true, features = ["default"], optional = true }
frame-system = { workspace = true, optional = true }
libsecp256k1 = { workspace = true, features = ["static-context", "hmac"], optional = true }
pallet-evm = { workspace = true, optional = true }
pallet-utility = { workspace = true, optional = true }
rlp = { workspace = true, optional = true }

[dev-dependencies]
num-traits.workspace = true
rand = { workspace = true, features = ["min_const_gen"] }

# test-ethereum dependencies
ethereum.workspace = true
fp-self-contained = { workspace = true, features = ["default"] }
frame-system.workspace = true
libsecp256k1 = { workspace = true, features = ["static-context", "hmac"] }
pallet-evm.workspace = true
pallet-utility.workspace = true
rlp.workspace = true

[features]
default = ["std"]
std = [
    "blake2/std",
    "domain-runtime-primitives/std",
    "frame-support/std",
    "hash-db/std",
    "parity-scale-codec/std",
    "rand/std",
    "rand_chacha/std",
    "rs_merkle/std",
    "scale-info/std",
    "serde/std",
    "sp-api/std",
    "sp-application-crypto/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-runtime-interface/std",
    "sp-state-machine/std",
    "sp-std/std",
    "sp-trie/std",
    "sp-version/std",
    "sp-weights/std",
    "subspace-core-primitives/std",
    "subspace-runtime-primitives/std",
    "trie-db/std",
    # test-ethereum dependencies
    "ethereum?/std",
    "fp-self-contained?/std",
    "frame-system?/std",
    "libsecp256k1?/std",
    "pallet-evm?/std",
    "rlp?/std",
]
runtime-benchmarks = []
test-ethereum = [
    "ethereum",
    "fp-self-contained",
    "frame-system",
    "libsecp256k1",
    "pallet-evm",
    "pallet-utility",
    "rlp",
]
