[package]
name = "pallet-transporter"
version = "0.1.0"
authors = ["Vedhavyas Singareddi <ved@subspace.network>"]
edition.workspace = true
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
description = "Subspace node pallet to move funds between domains."
include = [
    "/src",
    "/Cargo.toml",
    "/README.md",
]

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive"] }
domain-runtime-primitives.workspace = true
frame-benchmarking = { workspace = true, optional = true }
frame-support.workspace = true
frame-system.workspace = true
scale-info = { workspace = true, features = ["derive"] }
sp-core.workspace = true
sp-domains.workspace = true
sp-messenger.workspace = true
sp-runtime.workspace = true
sp-std.workspace = true

[dev-dependencies]
pallet-balances = { workspace = true, features = ["std"] }
pallet-messenger = { workspace = true, features = ["std"] }
sp-io.workspace = true
subspace-runtime-primitives.workspace = true

[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    "domain-runtime-primitives/std",
    "frame-benchmarking?/std",
    "frame-support/std",
    "frame-system/std",
    "scale-info/std",
    "sp-core/std",
    "sp-domains/std",
    "sp-messenger/std",
    "sp-runtime/std",
    "sp-std/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
    "frame-benchmarking/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "pallet-messenger/runtime-benchmarks",
    "sp-messenger/runtime-benchmarks",
]
