[package]
name = "sp-domain-digests"
version = "0.1.0"
authors = ["Vedhavyas Singareddi <ved@subspace.network>"]
edition.workspace = true
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
description = "Primitives of domain related digests"
include = [
    "/src",
    "/Cargo.toml",
]

[dependencies]
parity-scale-codec = { workspace = true, features = ["derive"] }
sp-runtime.workspace = true

[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    "sp-runtime/std",
]
