[package]
name = "subspace-malicious-operator"
version = "0.1.0"
authors = ["Subspace Labs <https://subspace.network>"]
description = "A Subspace Network Blockchain node."
edition.workspace = true
license = "0BSD"
build = "build.rs"
homepage = "https://subspace.network"
repository = "https://github.com/autonomys/subspace"
include = [
    "/src",
    "/build.rs",
    "/Cargo.toml",
    "/README.md"
]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
auto-id-domain-runtime.workspace = true
clap = { workspace = true, features = ["derive"] }
cross-domain-message-gossip.workspace = true
domain-client-message-relayer.workspace = true
domain-client-operator.workspace = true
domain-eth-service.workspace = true
domain-service.workspace = true
domain-runtime-primitives.workspace = true
evm-domain-runtime.workspace = true
fp-evm.workspace = true
frame-system.workspace = true
frame-system-rpc-runtime-api.workspace = true
futures.workspace = true
hex-literal.workspace = true
log.workspace = true
mimalloc.workspace = true
pallet-domains.workspace = true
pallet-messenger.workspace = true
pallet-transaction-payment.workspace = true
parity-scale-codec.workspace = true
pallet-subspace.workspace = true
pallet-sudo.workspace = true
sc-chain-spec.workspace = true
sc-cli.workspace = true
sc-client-api.workspace = true
sc-consensus-slots.workspace = true
sc-consensus-subspace.workspace = true
sc-domains.workspace = true
sc-network.workspace = true
sc-service.workspace = true
sc-storage-monitor.workspace = true
sc-subspace-chain-specs.workspace = true
sc-tracing.workspace = true
sc-transaction-pool-api.workspace = true
sc-network-sync.workspace = true
sc-utils.workspace = true
serde_json.workspace = true
sp-api.workspace = true
sp-blockchain.workspace = true
sp-block-builder.workspace = true
sp-consensus-subspace.workspace = true
sp-consensus-slots.workspace = true
sp-core.workspace = true
sp-domains.workspace = true
sp-domain-digests.workspace = true
sp-transaction-pool.workspace = true
sp-messenger.workspace = true
sp-runtime.workspace = true
sp-keystore.workspace = true
sp-keyring.workspace = true
sp-weights.workspace = true
subspace-core-primitives.workspace = true
subspace-networking.workspace = true
subspace-proof-of-space.workspace = true
subspace-runtime.workspace = true
subspace-runtime-primitives.workspace = true
subspace-service.workspace = true
thiserror.workspace = true
tokio.workspace = true
rand.workspace = true
tracing.workspace = true

[build-dependencies]
substrate-build-script-utils.workspace = true

[features]
default = []
